### ISSUE TITLE
WatsonORM.Sqlite not allow install in .NETFramework

### ISSUE THREAD

**Issue by MacKey-255** [jchristn/WatsonORM#1] opened 2020-08-17 02:30 UTC
Hello, I'm installing WatsonORM Library and The package WatsonORM.Sqlite only allow .NETStandard library and not .NETFramework. I go to download the code & compile for .NETFramework for it work! Fix that please, see TargetFramework in NuGet Packages. SAlu2s

**Comment by MacKey-255** [comment] 2020-08-17 02:42
The DatabaseWrapper.Sqlite use only .NETStandard too :( What I can do? All my project is with .NETFramework.

**Comment by jchristn** [comment] 2020-08-17 02:50
Hi @MacKey-255 thanks for your note.  I've had nothing but issues with Sqlite on .NET Framework - whether it is System.Data.SQLite or Microsoft.Data.Sqlite.  Both seem to have issues if it's not .NET Standard or .NET Core.  

I've had *some* success when manually installing Sqlite3 and then copying the DLL into the project and then copying into the output.  You're welcome to clone and modify the .csproj files to use:
```
<TargetFramework>net461</TargetFramework>
```
instead of
```
<TargetFramework>netstandard2.0</TargetFramework>
```
I would compile for both platforms and package it into NuGet if it wasn't such a burden to get right.  Sqlite is one of the main reasons I've moved most of my projects away from .NET Framework onto .NET Core.

**Comment by MacKey-255** [comment] 2020-08-17 04:55
I compile DatabaseWrapper.Sqlite & WatsonORM.Sqlite in .NETFramework and use this code:
```
using Watson.ORM.Core;
using Watson.ORM.Sqlite;
using System.Data.SQLite;

namespace Testing
{
    [Table("user")]
    class UserModel
    {
        [Column("id", true, DataTypes.Int, false)]
        public int Id { get; set; }
        [Column("username", false, DataTypes.Varchar, 255, false)]
        public string Username { get; set; }
        [Column("password", false, DataTypes.Varchar, 255, false)]

        public UserModel()
        {
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            if (!File.Exists($"./{Assembly.GetExecutingAssembly().GetName().Name}.db3"))
                SQLiteConnection.CreateFile($"{Assembly.GetExecutingAssembly().GetName().Name}.db3"); // Create Database
            // Test Watson Database
            WatsonORM Dbconnection = new WatsonORM(new DatabaseSettings($"{Assembly.GetExecutingAssembly().GetName().Name}.db3"));
            Dbconnection.InitializeDatabase();
            Dbconnection.InitializeTable(typeof(UserModel));
        }
    }
}
```
Look it error:
![query](https://user-images.githubusercontent.com/36246315/90358482-23114400-e024-11ea-809c-d8c167cc03bc.png)
... Now .... What I can do for fix it?
SAlu2s

**Comment by jchristn** [comment] 2020-08-17 15:45
Hi @MacKey-255 I retargeted DatabaseWrapper.Sqlite to include .NET Framework 4.6.1 and tested with the Test.Sqlite project and it passed in both debug and release mode.  I added it to NuGet (v3.2.1.1) here: https://www.nuget.org/packages/DatabaseWrapper.Sqlite/3.2.1.1  (commit is here: https://github.com/jchristn/DatabaseWrapper/commit/cea77b9b4dfd0389aad4e95f6fa9337b9659044c)

Once this is posted I'm also going to test in WatsonORM.  More to come.

**Comment by jchristn** [comment] 2020-08-17 15:57
Ok, here's the issue I'm running into.  You can see resolving it has been punted for a future release: https://github.com/dotnet/efcore/issues/19396

I run into this when testing directly against DatabaseWrapper, which has DatabaseWrapper.Sqlite as a dependency, which has Microsoft.Data.Sqlite as a dependency.

You can see Test.Sqlite, which references the project DatabaseWrapper.Sqlite directly, has the libraries copied to output when you build, whereas Test, which references the project DatabaseWrapper, does not copy the libraries when you build.

![image](https://user-images.githubusercontent.com/1421081/90416584-86709580-e067-11ea-9eee-a0eeb9610565.png)

This behavior will be the same with WatsonORM.Sqlite since it will reference DatabaseWrapper.Sqlite (which then references Microsoft.Data.Sqlite), and thus will not have the libraries copied.

**Comment by jchristn** [comment] 2020-08-17 16:03
(closed by accident, reopening, more to come)

**Comment by jchristn** [comment] 2020-08-17 16:07
Just confirmed using the WatsonORM Test.Sqlite project that it does **not** copy in the runtimes directory.  It also threw the exception.

Also confirmed that when I copy in the *runtimes* directory that it *works* as expected.

**Comment by jchristn** [comment] 2020-08-17 16:18
Uploaded WatsonORM.Sqlite.1.3.0.2 to NuGet with retarget to include .NET Framework 4.6.1: https://www.nuget.org/packages/WatsonORM.Sqlite/1.3.0.2

Updated WatsonORM with this updated dependency and also retargeted: https://www.nuget.org/packages/WatsonORM/1.3.0.2

Confirmed that with updated WatsonORM, the Test project also does not copy the runtimes directory:
![image](https://user-images.githubusercontent.com/1421081/90418727-5f679300-e06a-11ea-8903-1bbe21138c11.png)

Copied the runtimes directory into the .NET Framework 4.6.1 build output, and it worked.

The workaround, in the meantime, will be to copy the runtimes directory.  Closing this now.  Thanks for the nudge to re-target, we'll have to wait for an update from MS for a cleaner fix for Sqlite and .NET Framework.

**Closed by jchristn** 2020-08-17 16:18 UTC

**Comment by MacKey-255** [comment] 2020-08-19 23:04
Thanks, I love you work! SAlu2s

**Comment by jchristn** [comment] 2020-08-19 23:45
My pleasure, friend.  Have a great rest of your week!
